AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-dynamo

  Sample SAM Template for aws-lambda-dynamo

Globals:
  Function:
    Timeout: 5
    MemorySize: 256

Resources:

  Front:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: 'aws-lambda-dynamo-platform'
      CorsConfiguration:
        CorsRules:
        - AllowedOrigins:
            - '*'
          AllowedMethods:
            - 'GET'
            - 'POST'
            - 'PUT'
            - 'DELETE'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: 'index.html'

  DynamoDBTableResource:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'aws-lambda-dynamo-table-resource'
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: resourceName
        AttributeType: S
      KeySchema:
      - AttributeName: resourceName
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBTableToken:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'aws-lambda-dynamo-table-token'
      AttributeDefinitions:
      - AttributeName: token
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: token
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  DynamoDBTableUser:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'aws-lambda-dynamo-table-user'
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CorsLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.cors
      Runtime: nodejs8.10
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /login
            Method: options

  CorsResourceFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.cors
      Runtime: nodejs8.10
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /resource/{userId}
            Method: options

  CorsResourceFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.cors
      Runtime: nodejs8.10
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /resource/{userId}/{resourceId}
            Method: options

  CorsUserFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.cors
      Runtime: nodejs8.10
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /user
            Method: options

  CorsUserFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.cors
      Runtime: nodejs8.10
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: options


  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.login
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /login
            Method: post

  ListResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.listResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        ListResource:
          Type: Api
          Properties:
            Path: /resource/{userId}
            Method: get

  PostResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.postResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /resource/{userId}
            Method: post

  DeleteResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.deleteResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /resource/{userId}/{resourceId}
            Method: delete

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.getUser
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        GetUer:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: get

  ListUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.listUser
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /user
            Method: get

  PostUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.postUser
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /user
            Method: post

  PatchUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.patchUser
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        PutUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: patch

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.deleteUser
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_RESOURCE: 'aws-lambda-dynamo-table-resource'
          TABLE_USER: 'aws-lambda-dynamo-table-user'
          TABLE_TOKEN: 'aws-lambda-dynamo-table-token'
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: delete

Outputs:

  Api:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  Platform:
    Value: !GetAtt
    - Front
    - WebsiteURL
    Description: URL for platform website hosted on S3
  S3BucketSecureURL:
    Value: !Join
    - ''
    - - 'https://'
      - !GetAtt
        - Front
        - DomainName
    Description: Name of S3 bucket to hold platform website content
