AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-dynamo

  Sample SAM Template for aws-lambda-dynamo

Globals:
  Function:
    Timeout: 3

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'aws-lambda-dynamo-table'
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.getResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: 'aws-lambda-dynamo-table' # !Ref DynamoDBTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.listResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: 'aws-lambda-dynamo-table' # !Ref DynamoDBTable
      Events:
        ListResource:
          Type: Api
          Properties:
            Path: /resource
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.postResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: 'aws-lambda-dynamo-table' # !Ref DynamoDBTable
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /resource
            Method: post

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: index.deleteResource
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: 'aws-lambda-dynamo-table' # !Ref DynamoDBTable
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: delete

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
